schema:
  - name: golang-mysql-sample
    path: .
    commands:
      fmt:
        status: true
      install:
        status: true
      run:
        status: true
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - vendor
