[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gocraft/dbr"
  version = "2.4.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"
